<?php

namespace App\Components\Uxmal;

class FormButton extends Uxmal {

    protected string $label = 'defaultLabel';

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        if(!empty($this->attributes['label'])){
            $this->label = $this->attributes['label'];
            unset($this->attributes['modal-label']);
        }

    }

    public function toArray(): array
    {
        return parent::toArray() + [ 'label' => $this->label]; // TODO: Change the autogenerated stub
    }
}